# Utilise une image de base avec Python 3.10 (ou autre version souhaitée)
FROM python:3.14.0a1-bookworm

# Définit le répertoire de travail
WORKDIR /app


# # Copie les fichiers de votre application dans le conteneur
# COPY ./app /app

# # Installe les dépendances à partir d'un requirements.txt (si nécessaire)
# COPY requirements.txt .
# RUN pip install -r requirements.txt
RUN pip install mutagen