services:
  app:
    build:
      context:  ./Docker/python/     # Chemin du répertoire contenant le Dockerfile
      dockerfile: Dockerfile
    container_name: python_app_container
    volumes:
      - ./app:/app    # Monte le répertoire local `app` dans le conteneur
      - ./musicFolder:/musicFolder    # Monte le répertoire local `app` dans le conteneur
    command: python main.py